### ISSUE TITLE
[FR] Respect OS_type: unix

### ISSUE THREAD

**Issue by eddelbuettel** [r-universe-org/bugs#69]
CRAN allows to opt out of Windows builds.  It would be nice if r-universe followed suit.

It would be even nice if r-universe would let us opt out of macOS builds too because there are rare cases where packages cannot possibly build / are unlikely to succeed in a build on macOS.

**Comment by jeroen** [comment]
It actually works a bit different, it is mostly a front-end issue I think.

The front-end only interacts to our package repository. The front-end shows a ❌ in case no binary is found for a given package for that platform. It does not know *why* such a binary is not available (failure, skipped, or whatever), because the build system is entirely separate from the package repository. The front-end just displays which binaries are available.

I suppose what you are after is to somehow distinguish in the dashboard whether a package is unavailable for a given platform because it failed, or was skipped?

**Comment by eddelbuettel** [comment]
Interesting. I surmise that if you surveys N casual or experienced users what a red X means to them, most would say failure.  At least that is what it implies to me. And it is what we generally avoid in releases or even CI runs.

You describe as if you used the red X as a catch all response to 'not found', 'explicitly skipped', 'unknown'.  Maybe the display could actually try to convey more about the state.  Maybe not display anything for not found, and maybe a shaded icon for 'skipped'  -- reserving the red X for 'known recorded failure' ?

So this ticket may turn into two:  i) allowing me as author and maintainer of a package to express that I do not want you to waste your time on trying to build it on platforms where I know it will fail (think: littler on Windows; you currently ignore OS_type).  And ii) a more refined display of the states?   I care more about i) which is what I filed this for, but ii) could be useful too.

**Comment by jeroen** [comment]
I have updated the server and dashboard to special case packages with an `OS_type`: https://github.com/r-universe-org/dashboard/commit/5c1afcbf24ccd72966135b10b77981497229b36b. Those packages should no longer show a ❌ on your dashboard: https://eddelbuettel.r-universe.dev/ui#builds


Customising the CI build steps for single packages is pretty complex. There may be a way, but there are very few packages with an OS_type right now (both owned by you) so for now this is not high priority, but i'll keep it in mind.

**Comment by eddelbuettel** [comment]
I would have closed it earlier but methinks the 'would like to block macOS builds' part is still unanswered.  As such, more like 'partially closed'.
