### ISSUE TITLE
Universe in prepetual backlog

### ISSUE THREAD

**Issue by zkamvar** [r-universe-org/bugs#79]
As of right now, this run has been queueing for 28.5 hours

https://github.com/r-universe/carpentries/runs/3175205655?check_suite_focus=true

```
Started 1d 3h 27m 9s ago
Can't find any online and idle self-hosted or hosted runner in the current repository, account/organization that matches the required labels: 'windows-latest'
Waiting for a self-hosted or a hosted runner to pickup this job...
```

This backlog is causing downstream builds to also stall, such as this build that has been queueing for 3.5 hours: https://github.com/r-universe/carpentries/runs/3185244714?check_suite_focus=true

Is there a way to cancel or kickstart these runs?

**Comment by jeroen** [comment]
Yes very weird. It looks like a problem in the GitHub actions system. I'm looking for a solution

**Comment by jeroen** [comment]
We have updated the r-univeres plan this morning, which hopefully should give is more concurrent builds. 

It looks like new builds are running again, however builds that were triggered before we upgraded still seem to be stuck. I think the problem will resolve itself, because gitHub actions are automatically cancelled after 24h.
